### PR TITLE
Simpler Dolt usage

### PR DESCRIPTION
**Pull request by six8**
- Made API the base class for extending Dolt for APIs
- Dolt now accepts a base_url for simple requests that don't need a subclass
- Added documentation and tests

### CODE REVIEW

**Comment by tswicegood** [comment]
This looks cool.  What about inverting `Api` and `Dolt` so `Dolt` remains the base one and there's sub-class of it that provides the base behavior.  Maybe `SimpleApi` or some such?  That would maintain backwards compatibility.

**Comment by six8** [comment]
Ok, done.

**Comment by tswicegood** [comment]
I _love_ the new class name!

**Comment by six8** [comment]
I figured only a Simpleton could be simpler than a Dolt

**Pull request merged**
