### PR TITLE
Initial pass at making this work with @requests

### PR DESCRIPTION
**Pull request by tswicegood**

### CODE REVIEW

**Comment by tswicegood** [comment]
Still left to do:
- Figure out how to handle auth/pass in arbitrary params to the various `requests` methods
- Update/verify that all of the existing API code to works with requests

**Comment by JNRowe** [comment]
With my "curious user" hat on and possibly failing to read between the lines in 1f7ccc6306f394edffe1725f216e31b4973ddec7 …

How likely is the move to `requests`?  Is it a case of solving the TODO items and merging, or just a viability test?

**Comment by tswicegood** [comment]
@JNRowe Pretty likely, assuming I can do it without breaking everything.  :-)

The idea is to remove the reliance on `httplib2` by becoming a higher-level tool on top of `requests`.  When I started Dolt, that wasn't an option.  There's a few things that still need to be worked out which are listed in the comment above.

The big one is having a way to do authentication since `requests` does that later in the process.

**Comment by JNRowe** [comment]
@tswicegood Thanks for the thorough reply!

**Pull request closed without merging**
